version: '3.3'
services:
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./openvpn-data:/etc/openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - EASYRSA_BATCH=1
    entrypoint: /bin/sh -c "/scripts/init-openvpn.sh && ovpn_run"